### ISSUE TITLE
1.0 Goals/TODO

### ISSUE THREAD

**Issue by zackhasacat** [zackhasacat/ResdayniaVault#1]
- [ ] Furnish unfinished areas
- [ ] Create Quest List, implement it
- [ ] Construct player home
- [ ] Implement power system, for if power goes out, then make the vault dark
- [ ] Put in Telvanni homes/shops
- [ ] Add in creature merchant(Talking kwama worker?) OR, allow bring in MCM
- [ ] Build Daedric shrine, add stairs/platform to the shrine after it is discovered
- [ ] Vampire takeover quest
- [ ] Larger door to main area
